# 总环境配置

# spring
spring:
  # profile
  profiles:
    active: dev
  # redis
  redis:
    host: 139.199.16.239
    port: 6379
    password: xubenchi
    timeout: 0
    pool:
      max-active: 9
      min-idle: 0
      max-idle: 8
      max-wait: -1
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.199.16.239:3306/house_rent?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: XUBENCHI789xbc@
    # druid
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 300
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
  # jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # jackson
  jackson:
    default-property-inclusion: non_empty
  # mail
  mail:
    host: smtp.qq.com
    username: 806569552@qq.com
    password: itvlgudqipshbbgf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# mybatis-plus
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.leaf.xadmin.entity, com.leaf.xadmin.constants
    type-enums-package: com.leaf.xadmin.enums
    global-config:
      # 主键类型  0: "数据库ID自增", 1: "用户输入ID", 2: "全局唯一ID (数字类型唯一ID)", 3: "全局唯一ID UUID";
      id-type: 2
      # 字段策略 0: "忽略判断", 1: "非 NULL 判断"), 2: "非空判断";
      field-strategy: 2
      # 驼峰下划线转换
      db-column-underline: true
      # 刷新mapper 调试神器
      refresh-mapper: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false

# logging
logging:
  config: classpath:logback/logback.xml







