# 总环境配置

# spring
spring:
  # profile
  profiles:
    active: dev
  # redis
  redis:
    host: 139.199.16.239
    port: 6379
    password: 123456
    timeout: 0
    pool:
      max-active: 9
      min-idle: 0
      max-idle: 8
      max-wait: -1
  # jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # jackson
  jackson:
    default-property-inclusion: non_empty
  # mail
  mail:
    host: smtp.qq.com
    username: 806569552@qq.com
    password: itvlgudqipshbbgf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # datasource
  datasource:
    druid:
      auth:
        url: jdbc:mysql://localhost:3306/db_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      bg:
        url: jdbc:mysql://localhost:3306/db_bg?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      front:
        url: jdbc:mysql://localhost:3306/db_front?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      qrtz:
        url: jdbc:mysql://localhost:3306/db_qrtz?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
  # aop
  aop:
    auto: true
    proxy-target-class: true
# logging
logging:
  config: classpath:logback/logback.xml