# 总环境配置

# spring
spring:
  # profile
  profiles:
    active: dev
  # redis
  redis:
    host: 139.199.16.239
    port: 6379
    password: 123456
    timeout: 0
    pool:
      max-active: 9
      min-idle: 0
      max-idle: 8
      max-wait: -1
  # jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # jackson
  jackson:
    default-property-inclusion: non_empty
  # mail
  mail:
    host: smtp.qq.com
    username: 806569552@qq.com
    password: itvlgudqipshbbgf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# logging
logging:
  config: classpath:logback/logback.xml